#!/bin/bash
#
## by makeme v.2022.02.14
#
#BASEPATH='/storage/games/flare'
#mkdir -p $BASEPATH
BASEPATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
ENGINEPATH=$BASEPATH/flare-engine
GAMEPATH=$BASEPATH/flare-game
FLAREVERSION=$(./flare --version 2>&1 | awk '{print $3}')
LATESTVERSION=$(git log -1 | grep -i version | awk '{print $2}')
#LATESTVERSION='1.13.03' # for testing
# 
gameupdate()
{
        cd $ENGINEPATH && git pull
        cd $GAMEPATH && git pull
        cd $ENGINEPATH
        cmake . && make
}

gameinstall()
{
        cd $BASEPATH && \
        git clone https://github.com/flareteam/flare-engine && \
        git clone https://github.com/flareteam/flare-game
        cd flare-engine
        cmake . && make
        cd ../flare-game
        ln -s ../flare-engine/flare flare
        cd mods
        ln -s ../../flare-engine/mods/default default
}
asktolaunchthegame()
{
        read -p "Are you sure? (Answer Yy or Nn) " -n 1 -r
        echo    # (optional) move to a new line
        if [[ ! $REPLY =~ ^[Yy]$ ]]
        then
                exit 1
        else
                cd $GAMEPATH && ./flare
        fi
}
#
echo "Checking if the game is already installed..."
cd $GAMEPATH

if [ -d "$ENGINEPATH" ] && [ -d "$GAMEPATH" ]
then
        echo "Found game and engine directories!" 
        echo "Checking for NEW version..."
        echo "Flare Version:" $FLAREVERSION
        echo "Latest Version:" $LATESTVERSION

        if [[ "$FLAREVERSION" == "$LATESTVERSION" ]]
        then    
                echo "No NEW version."
                ./flare
        else
                echo "NEW version found! Updating..."
                gameupdate
        fi
else
        echo ""
        echo "There is no game found in here. Installing..."
        gameinstall && echo "Installation complete"
        asktolaunchthegame
fi
